image: ddgg/oop_2020:build_v1

pipelines:
  default:
    - step:
        script:
          - pushd galeria_zdjec/
          -   mkdir build-Project && pushd build-Project
          -     qmake ../Project
          -     make -j4
          -     pushd tests/tst_testy
          -       LD_LIBRARY_PATH=../../utils -o test_detail.xml,xunitxml
          -     popd
          -   popd
          - popd
          - .ci/collect_reports.sh
