image: ddgg/oop_2020:build_v1

pipelines:
  default:
    - step:
        script:
          - pushd galeria_zdjec/
          -   mkdir build-project && pushd build-project
          -     qmake ../Project
          -     make -j4 
          -   popd
          - popd
          - .ci/collect_reports.sh
