ARG FROM

FROM $FROM

USER root

RUN apt-get update \ 
 && apt-get install -y git cmake g++ plantuml qt5-default qtdeclarative5-dev qtquickcontrols2-5-dev qml-module-qtquick-controls2 \
 && rm -rf /var/lib/apt/lists/*

USER ${IMAGE_USER}
WORKDIR /home/${IMAGE_USER}

CMD ["bash"]
